#!/usr/bin/env bash
# GitLab + GitLab Runner installer.
#
# Values come from the environment or .env, and are asked for when missing.
#
# Usage: bash ./install.sh [--yes] [--no-start] [--regenerate]
#        bash ./install.sh --runner | --update-env
#   --yes, -y      never prompt; fail if a required value is missing
#   --no-start     write the configuration but do not start anything
#   --regenerate   write omnibus_config.rb again from .env (it is kept by default)
#   --runner       register a runner (asks for the runner token)
#   --update-env   rebuild .env from .env.sample, keep your values, then exit

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

ENV_FILE=".env"
OMNIBUS_FILE="omnibus_config.rb"
YES=false; START=true; REGENERATE=false; MODE=install; NEW_INSTALL=false

die()  { echo "Error: $*" >&2; exit 1; }
info() { echo "==> $*"; }

for arg in "$@"; do
    case "$arg" in
        --yes|-y)     YES=true ;;
        --no-start)   START=false ;;
        --regenerate) REGENERATE=true ;;
        --runner)     MODE=runner ;;
        --update-env) MODE=update-env ;;
        -h|--help)    sed -n '2,/^set -euo/p' "$0" | sed '$d; s/^# \{0,1\}//'; exit 0 ;;
        *)            die "unknown option: $arg (see --help)" ;;
    esac
done
[[ -t 0 ]] || YES=true

load_env() {
    local line key val
    [[ -f "$ENV_FILE" ]] || return 0
    while IFS= read -r line || [[ -n "$line" ]]; do
        [[ "$line" =~ ^([A-Za-z_][A-Za-z0-9_]*)=(.*)$ ]] || continue
        key="${BASH_REMATCH[1]}"; val="${BASH_REMATCH[2]}"
        [[ "$val" =~ ^\'(.*)\'$ || "$val" =~ ^\"(.*)\"$ ]] && val="${BASH_REMATCH[1]}"
        [[ -n "${!key:-}" ]] || export "$key=$val"
    done < "$ENV_FILE"
}

quote() {
    if [[ "$1" =~ ^[A-Za-z0-9._:/@+,=-]+$ ]]; then printf '%s' "$1"
    else printf "'%s'" "${1//\'/\'\\\'\'}"; fi
}

write_env() {
    local tmp line key other; tmp="$(mktemp)"
    while IFS= read -r line; do
        if [[ "$line" =~ ^(#[[:space:]]*)?([A-Z][A-Z0-9_]*)= && -n "${!BASH_REMATCH[2]:-}" ]]; then
            key="${BASH_REMATCH[2]}"; line="$key=$(quote "${!key}")"
        fi
        echo "$line"
    done < .env.sample > "$tmp"
    other="$(grep -E '^[A-Za-z_][A-Za-z0-9_]*=' "$ENV_FILE" 2>/dev/null | while IFS= read -r line; do
        grep -qE "^#?[[:space:]]*${line%%=*}=" .env.sample || echo "$line"
    done || true)"
    [[ -z "$other" ]] || printf '\n# Other settings kept from the previous %s\n%s\n' "$ENV_FILE" "$other" >> "$tmp"
    cat "$tmp" > "$ENV_FILE"; chmod 600 "$ENV_FILE"; rm -f "$tmp"
}

ask() {
    local var="$1" prompt="$2" default="${3:-}" reply
    [[ -n "${!var:-}" ]] && return 0
    if $YES; then
        [[ -n "$default" ]] || die "$var is not set (set it in the environment or $ENV_FILE)"
        printf -v "$var" '%s' "$default"; return 0
    fi
    read -r -p "$prompt${default:+ [$default]}: " reply
    reply="${reply:-$default}"
    [[ -n "$reply" ]] || die "$var is required"
    printf -v "$var" '%s' "$reply"
}

ask_optional() {
    local var="$1" reply=""
    [[ -z "${!var+x}" ]] || return 0
    $YES || read -r -p "$2: " reply
    printf -v "$var" '%s' "$reply"
}

ask_secret() {
    local var="$1" min="${3:-8}" p1 p2
    [[ -n "${!var:-}" ]] && return 0
    $YES && die "$var is not set (set it in the environment or $ENV_FILE)"
    while :; do
        read -r -s -p "$2: " p1; echo
        read -r -s -p "Repeat: " p2; echo
        [[ "$p1" == "$p2" && ${#p1} -ge $min ]] && break
        echo "The values must match and have at least $min characters."
    done
    printf -v "$var" '%s' "$p1"
}

compose() {
    if docker compose version >/dev/null 2>&1; then docker compose "$@"
    else docker-compose "$@"; fi
}

build_compose() {
    export COMPOSE_FILE="docker-compose.yaml"
    export COMPOSE_PROFILES="runner"
    if [[ "$INSTALL_TYPE" == "gitlab" ]]; then
        COMPOSE_PROFILES="gitlab,runner"
        [[ -z "${REGISTRY_DOMAIN:-}" ]] || COMPOSE_FILE+=":docker-compose.registry.yaml"
    fi
    if [[ -f docker-compose.override.yaml ]]; then
        COMPOSE_FILE+=":docker-compose.override.yaml"
        info "Using docker-compose.override.yaml"
    fi
}

create_volumes() {
    local v
    for v in gitlab-data gitlab-config gitlab-logs; do
        docker volume inspect "$v" >/dev/null 2>&1 && continue
        docker volume create "$v" >/dev/null
        info "Created volume $v"
        [[ "$v" != gitlab-data ]] || NEW_INSTALL=true
    done
}

rb() { local s="${1//\\/\\\\}"; s="${s//\"/\\\"}"; printf '%s' "${s//#/\\#}"; }

render_omnibus() {
    if [[ -f "$OMNIBUS_FILE" ]] && ! $REGENERATE; then
        info "Keeping $OMNIBUS_FILE"
        return 0
    fi
    ( umask 077
      {
        echo "# Generated by install.sh. Kept on re-runs; --regenerate writes it again."
        echo "external_url \"https://$(rb "$GITLAB_DOMAIN")\""
        echo "gitlab_rails[\"time_zone\"] = \"$(rb "${GITLAB_TIMEZONE:-UTC}")\""
        echo
        if [[ -n "${SMTP_HOST:-}" ]]; then
            local from="${SMTP_FROM:-${SMTP_USER:-}}"
            echo "gitlab_rails[\"smtp_enable\"] = true"
            echo "gitlab_rails[\"smtp_address\"] = \"$(rb "$SMTP_HOST")\""
            echo "gitlab_rails[\"smtp_port\"] = ${SMTP_PORT:-587}"
            echo "gitlab_rails[\"smtp_user_name\"] = \"$(rb "${SMTP_USER:-}")\""
            echo "gitlab_rails[\"smtp_password\"] = \"$(rb "${SMTP_PASSWORD:-}")\""
            echo "gitlab_rails[\"smtp_domain\"] = \"$(rb "${SMTP_DOMAIN:-$SMTP_HOST}")\""
            echo "gitlab_rails[\"gitlab_email_from\"] = \"$(rb "$from")\""
            echo "gitlab_rails[\"gitlab_email_reply_to\"] = \"$(rb "$from")\""
            [[ "${SMTP_VERIFY_NONE:-true}" != "true" ]] || echo "gitlab_rails['smtp_openssl_verify_mode'] = 'none'"
        else
            echo "gitlab_rails[\"smtp_enable\"] = false"
        fi
        cat <<'EOF'

nginx["listen_port"] = 80
nginx["listen_https"] = false
nginx["redirect_http_to_https"] = false
nginx['proxy_set_headers'] = {
  'X-Forwarded-Proto' => 'https',
  'X-Forwarded-Ssl' => 'on'
}
letsencrypt["enable"] = false
EOF
        if [[ "${GITLAB_LOW_MEMORY:-true}" == "true" ]]; then
            cat <<'EOF'

puma['worker_processes'] = 2
puma["min_threads"] = 2
puma["max_threads"] = 4
puma["per_worker_max_memory_mb"] = 1200
sidekiq['concurrency'] = 5
alertmanager['enable'] = false
node_exporter['enable'] = false
postgres_exporter['enable'] = false
prometheus_monitoring['enable'] = false
prometheus['enable'] = false
puma['exporter_enabled'] = false
redis_exporter['enable'] = false
sidekiq['metrics_enabled'] = false
gitlab_rails['env'] = { 'MALLOC_CONF' => 'dirty_decay_ms:1000,muzzy_decay_ms:1000' }
gitaly['env'] = {
  'MALLOC_CONF' => 'dirty_decay_ms:1000,muzzy_decay_ms:1000',
  'GITALY_COMMAND_SPAWN_MAX_PARALLEL' => '2'
}
EOF
        fi
        if [[ -n "${REGISTRY_DOMAIN:-}" ]]; then
            echo
            echo "registry_external_url \"https://$(rb "$REGISTRY_DOMAIN")\""
            cat <<'EOF'
registry_nginx["listen_port"] = 5100
registry_nginx["listen_https"] = false
registry_nginx["proxy_set_headers"] = {
  "X-Forwarded-Proto" => "https",
  "X-Forwarded-Ssl" => "on"
}
EOF
        fi
      } > "$OMNIBUS_FILE" )
    info "Wrote $OMNIBUS_FILE"
}

wait_healthy() {
    local i
    info "Waiting for GitLab to become healthy"
    for i in $(seq 1 90); do
        [[ "$(docker inspect gitlab --format '{{.State.Health.Status}}' 2>/dev/null)" == "healthy" ]] && return 0
        sleep 10
    done
    return 1
}

# The password is passed through the environment, not the command line.
set_root_password() {
    ROOT_PW="$1" docker exec -e ROOT_PW gitlab gitlab-rails runner "
        u = User.find_by_username('root')
        u.password = u.password_confirmation = ENV['ROOT_PW']
        u.password_automatically_set = false
        u.save!"
    info "Set the root password"
}

register_runner() {
    ask RUNNER_URL "GitLab URL for the runner" "http://gitlab:80"
    ask RUNNER_TOKEN "Runner authentication token (glrt-...)"
    ask RUNNER_NAME "Runner name" "$(hostname)"
    ask RUNNER_VERSION "Runner version" "v19.4.1"
    [[ "$RUNNER_TOKEN" == glrt-* ]] || die "RUNNER_TOKEN must be an authentication token (glrt-...)"
    export RUNNER_VERSION
    export COMPOSE_PROFILES="${COMPOSE_PROFILES:-runner}"

    local args=(register --non-interactive --url "$RUNNER_URL" --token "$RUNNER_TOKEN"
        --name "$RUNNER_NAME" --executor docker
        --docker-image "${RUNNER_DOCKER_IMAGE:-docker:latest}"
        --docker-pull-policy if-not-present --docker-volumes /cache
        --limit "${RUNNER_LIMIT:-2}" --request-concurrency "${RUNNER_LIMIT:-2}")
    [[ "${RUNNER_PRIVILEGED:-true}" != "true" ]] || args+=(--docker-privileged)
    local mem="${RUNNER_MEMORY-2g}"   # empty = no memory limit
    [[ -z "$mem" ]] || args+=(--docker-memory "$mem" --docker-memory-swap "$mem")

    mkdir -p gitlab-runner
    compose run --rm --no-deps gitlab-runner "${args[@]}"
    sed -i "s/^concurrent = .*/concurrent = ${RUNNER_CONCURRENT:-2}/" gitlab-runner/config.toml
    chmod 600 gitlab-runner/config.toml
    ! $START || compose up -d gitlab-runner
    unset RUNNER_TOKEN
    write_env
    info "Runner registered"
}

install() {
    local host_re='^([A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?\.)+[A-Za-z]{2,}$'
    ask INSTALL_TYPE "Install type: gitlab (GitLab and runner) or runner (runner only)" "gitlab"
    [[ "$INSTALL_TYPE" =~ ^(gitlab|runner)$ ]] || die "INSTALL_TYPE must be gitlab or runner"

    if [[ "$INSTALL_TYPE" == "gitlab" ]]; then
        ask GITLAB_DOMAIN "GitLab domain (e.g. gitlab.example.com)"
        ask GITLAB_VERSION "GitLab version" "19.4.1-ee.0"
        if [[ ! -f "$OMNIBUS_FILE" ]] || $REGENERATE; then
            ask_optional REGISTRY_DOMAIN "Container registry domain (empty = no registry)"
            ask GITLAB_TIMEZONE "Time zone" "UTC"
            ask_optional SMTP_HOST "SMTP host for email (empty = no email)"
            if [[ -n "${SMTP_HOST:-}" ]]; then
                ask SMTP_PORT "SMTP port" "587"
                ask SMTP_USER "SMTP user"
                ask_secret SMTP_PASSWORD "SMTP password" 1
            fi
        fi
        [[ "$GITLAB_DOMAIN" =~ $host_re ]] || die "invalid GITLAB_DOMAIN: $GITLAB_DOMAIN"
        [[ -z "${REGISTRY_DOMAIN:-}" || "$REGISTRY_DOMAIN" =~ $host_re ]] || die "invalid REGISTRY_DOMAIN: $REGISTRY_DOMAIN"
    else
        ask RUNNER_URL "GitLab URL for the runner (e.g. https://gitlab.example.com)"
    fi
    ask RUNNER_VERSION "Runner version" "v19.4.1"
    build_compose

    if [[ "$INSTALL_TYPE" == "gitlab" ]]; then
        ! $START || create_volumes
        render_omnibus
        ! $NEW_INSTALL || ask_secret GITLAB_ROOT_PASSWORD "Password for the GitLab 'root' administrator"
    fi
    mkdir -p gitlab-runner

    local root_pw="${GITLAB_ROOT_PASSWORD:-}"
    unset GITLAB_ROOT_PASSWORD RUNNER_TOKEN
    write_env
    info "Saved settings to $ENV_FILE"

    if $START; then
        local answer=y
        $YES || read -r -p "Start now? [Y/n]: " answer
        if [[ "${answer:-y}" =~ ^[Yy] ]]; then
            compose up -d
            if $NEW_INSTALL && [[ -n "$root_pw" ]]; then
                wait_healthy && set_root_password "$root_pw" \
                    || echo "GitLab is not healthy yet. Set the root password later: docker exec -it gitlab gitlab-rake \"gitlab:password:reset[root]\""
            fi
        fi
    fi

    echo
    if [[ "$INSTALL_TYPE" == "gitlab" ]]; then
        echo "GitLab: https://$GITLAB_DOMAIN (user: root)"
        [[ -z "${REGISTRY_DOMAIN:-}" ]] || echo "Registry: https://$REGISTRY_DOMAIN"
    fi
    echo "Next: bash ./install.sh --runner (needs a runner token from GitLab)"
}

command -v docker >/dev/null 2>&1 || die "docker is not installed"
load_env
case "$MODE" in
    install)    install ;;
    runner)     register_runner ;;
    update-env) unset GITLAB_ROOT_PASSWORD RUNNER_TOKEN
                [[ -z "${INSTALL_TYPE:-}" ]] || build_compose   # pick up a new override file
                write_env
                info "Updated $ENV_FILE from .env.sample" ;;
esac
